version: '3.8'
services:
  app:
    build: .
    container_name: tudo-thrifting-server
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/tudo-thrifting-db # Example MongoDB URI
    volumes:
      - .:/app
    networks:
      - nest-mongo-network

  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - nest-mongo-network

volumes:
  mongo-data:
    driver: local

networks:
  nest-mongo-network:
    driver: bridge
